### ISSUE TITLE
Windows 11 "Do not disturb"

### ISSUE THREAD

**Issue by RedAstaire1** [DrinkWaterUWP/DrinkWater#7]
Good morning,

Your tool is really very useful to help us keep ourselves hydrated.

Only, when Do Not Disturb mode is on, we don't get any notifications, despite the fact that I have enabled "Show important notifications when Do Not Disturb is on", but it still doesn't work .

It's just enough that I play a video in full screen for the notification to be deactivated... That's too bad. Is it possible to do something for this? THANKS

**Comment by DrinkWaterUWP** [comment]
Hi @RedAstaire1, in order to enable Drink Water notifications while in Do Not Disturb mode, please follow these steps:

1. Open the notification center and turn on Do Not Disturb mode.
![image](https://user-images.githubusercontent.com/82997702/235355664-f2f55950-611f-4f8a-add3-696da9c3f93e.png)
2. Click on "Notification Settings" in the notification center.
![image](https://user-images.githubusercontent.com/82997702/235355631-209711d4-5db3-442c-84e7-3853c156ad9a.png)
3. Select "Set priority notifications."
4. Choose "Add apps," and then select "Drink Water" from the list.
